### ISSUE TITLE
Anko for RecyclerView

### ISSUE THREAD

**Issue by amouly** [antoniolg/Kotlin-for-Android-Developers#1]
Can't we use Anko for the RecyclerView here?:

https://github.com/antoniolg/Kotlin-for-Android-Developers/blob/master/app/src/main/java/com/antonioleiva/weatherapp/activities/MainActivity.kt#L28

**Comment by sargunster** [comment]
Using the Kotlin Android Extension would be even better,

**Comment by antoniolg** [comment]
I missed this issue, sorry... Yeah, I didn't use it at that moment because it was a future part of the book and I hadn't explained it yet. This App is now using Kotlin Android Extensions and Anko wherever it helps writing an easier code.

**Comment by amouly** [comment]
Thanks! :+1:
