### ISSUE TITLE
Book Errata: 7.3 Extension functions

### ISSUE THREAD

**Issue by bytehala** [antoniolg/Kotlin-for-Android-Developers#13]
Paragraph 2, Sentence 1 of 7.3 Extension functions

> For instance, we can create a toast function that doesn't the context as parameter, which could ...

Should it be like this:
For instance, we can create a toast function that doesn't **need** the context as parameter...

(Inserted "need")

**Comment by antoniolg** [comment]
Thanks so much! Fixed and ready for the next release (hopefully in a few days).
