### ISSUE TITLE
Book Errata: 7.2 Start using Anko

### ISSUE THREAD

**Issue by bytehala** [antoniolg/Kotlin-for-Android-Developers#14]
The following code sample does not work anymore:
`val forecastList: RecyclerView = find(R.id.forecast_list)`

Use this instead:
`val forecastList = find<RecyclerView>(R.id.forecast_list)`

**Comment by bytehala** [comment]
I mean I know you know that, but the book's sample code is outdated.. that was confusing for me.

**Comment by antoniolg** [comment]
Sorry, but both are valid right? In fact the code in https://github.com/antoniolg/Kotlin-for-Android-Developers/tree/chapter-7 is like that and it's compiling and running.

You can be explicit on the type, and the generic function will infer it, or you can be explicit on the generic function and the type will be inferred.

**Comment by bytehala** [comment]
Oh? Hmmm.. What version should I check? Kotlin? Anko? Because it wasn't compiling on my setup.

**Comment by antoniolg** [comment]
Nothing probably 🤔 . That's all a language feature, so it should be working with any kotlin or anko versions... Which versions are you using?

**Comment by bytehala** [comment]
Seems like you're right. I might have been using
`find(R.id.forecast_list) as RecyclerView`

I'll get you yet! 😛
