### ISSUE TITLE
errors importing in androdiStudio3 preview2

### ISSUE THREAD

**Issue by maxlinux2000** [antoniolg/Kotlin-for-Android-Developers#19]
importing this demo app in the last canary Android Studio, I found some errors during the sync.

please modify the code of "app" like:

```
    compile "org.jetbrains.anko:anko:0.10.1"
    compile "org.jetbrains.anko:anko-common:0.10.1"
    compile "org.jetbrains.anko:anko-sqlite:0.10.1n"
    compile "org.jetbrains.anko:anko-coroutines:0.10.1"

```

this is enounght to fix the errors of sync

regards
MaX

**Comment by antoniolg** [comment]
Are you sure that's making the project work? There's a bug on sqlite for 0.10.1, that's why I sticked to 0.10.0

**Comment by antoniolg** [comment]
Closing this as AS3 is already released, and received no response since August
