### ISSUE TITLE
API calls return an error 401

### ISSUE THREAD

**Issue by lucamtudor** [antoniolg/Kotlin-for-Android-Developers#2]
Starting 9 October 2015, the OpenWeatherMap API requires a valid APPID for access. You just need to register an account with them.

Eg:
http://api.openweathermap.org/data/2.5/forecast/city?id=524901&APPID={APIKEY}

**Comment by antoniolg** [comment]
Thanks, had a fix for that but forgot pushing it. When I review the book, I'll add it to its proper chapter and commit, but I wanted to add a quick fix for now.
