### ISSUE TITLE
failed to run from master branch 

### ISSUE THREAD

**Issue by 1abid** [antoniolg/Kotlin-for-Android-Developers#20]
I am facing a problem running the app from 'master' , gradle task is failing with these error 

<img width="1802" alt="screen shot 2017-10-04 at 12 39 20 am" src="https://user-images.githubusercontent.com/6067801/31142685-da1231ae-a89c-11e7-83c7-2e3b4793a021.png">

I have searched with this error on StackOverFlow . Most of the thread came with solution adding kotlin android plugin , which is already added . Am I missing something @antoniolg

**Comment by antoniolg** [comment]
I haven't been able to repo, but some people mentioned it fixes by updating Anko version.

 I updated the the main branch (https://github.com/antoniolg/Kotlin-for-Android-Developers/commit/c290ebc8e6a2b82cacc00af18a9d460f46329404) as a patch until I release a new update of the book.

My plan was to wait until 1.2 is released, but I think I'll start right away to have this fixed ASAP.
