### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Achenglove** [antoniolg/Kotlin-for-Android-Developers#23]
![image](https://user-images.githubusercontent.com/26593441/32205993-7f4a5e44-be2d-11e7-9090-02f047761878.png)

**Comment by KevinLaRosa** [comment]
I've updated the anko version to 0.10.2 in the build.gradle to resolve this issue.

**Comment by antoniolg** [comment]
@KevinLaRosa do you know how it's related? Are you using API 26 or something similar?

**Comment by KevinLaRosa** [comment]
I've no idea. I've only found that anko-coroutines before the 0.10.1 doesn't work. I'm using  compileSdkVersion 26 and buildToolsVersion 26.0.2.

**Comment by antoniolg** [comment]
Looks like Anko needs 0.10.2 to work with API 26 then... I'll do some tests and upload a fix ASAP.

thanks!

**Comment by antoniolg** [comment]
I updated the the main branch (https://github.com/antoniolg/Kotlin-for-Android-Developers/commit/c290ebc8e6a2b82cacc00af18a9d460f46329404) as a patch until I release a new update of the book.

My plan was to wait until 1.2 is released, but I think I'll start right away to have this fixed ASAP.
