### ISSUE TITLE
Chapter 8 Code example doesn't run as described

### ISSUE THREAD

**Issue by abunur** [antoniolg/Kotlin-for-Android-Developers#25]
Running the code from Chapter 8 branch, the toast never actually occurs.  This is the error log I see in Logcat:

11-19 16:57:50.053 5203-5203/? I/zygote: Not late-enabling -Xcheck:jni (already on)
11-19 16:57:50.064 5203-5203/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
11-19 16:57:50.275 5203-5203/com.antonioleiva.weatherapp I/InstantRun: starting instant run server: is main process
11-19 16:57:50.462 5203-5229/com.antonioleiva.weatherapp D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-19 16:57:50.489 5203-5231/com.antonioleiva.weatherapp D/OpenGLRenderer: HWUI GL Pipeline
                                                                           
                                                                           [ 11-19 16:57:50.541  1902: 2245 W/         ]
                                                                           Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
11-19 16:57:50.545 5203-5229/com.antonioleiva.weatherapp W/System.err: java.io.FileNotFoundException: http://api.openweathermap.org/data/2.5/forecast/daily?APPID=15646a06818f61f7b8d7823ca833e1ce&q=94043&mode=json&units=metric&cnt=7
11-19 16:57:50.546 5203-5229/com.antonioleiva.weatherapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
11-19 16:57:50.551 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.net.URL.openStream(URL.java:1058)
11-19 16:57:50.553 5203-5229/com.antonioleiva.weatherapp W/System.err:     at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:144)
11-19 16:57:50.562 5203-5229/com.antonioleiva.weatherapp W/System.err:     at com.antonioleiva.weatherapp.data.Request.run(Request.kt:9)
11-19 16:57:50.563 5203-5229/com.antonioleiva.weatherapp W/System.err:     at com.antonioleiva.weatherapp.ui.activities.MainActivity$onCreate$1.invoke(MainActivity.kt:39)
11-19 16:57:50.563 5203-5229/com.antonioleiva.weatherapp W/System.err:     at com.antonioleiva.weatherapp.ui.activities.MainActivity$onCreate$1.invoke(MainActivity.kt:15)
11-19 16:57:50.563 5203-5229/com.antonioleiva.weatherapp W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:140)
11-19 16:57:50.569 5203-5229/com.antonioleiva.weatherapp W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
11-19 16:57:50.570 5203-5229/com.antonioleiva.weatherapp W/System.err:     at org.jetbrains.anko.AsyncKt$sam$Callable$761a5578.call(Unknown Source:2)
11-19 16:57:50.570 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-19 16:57:50.571 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
11-19 16:57:50.572 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-19 16:57:50.573 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-19 16:57:50.574 5203-5229/com.antonioleiva.weatherapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
11-19 16:57:51.029 5203-5231/com.antonioleiva.weatherapp I/OpenGLRenderer: Initialized EGL, version 1.4
11-19 16:57:51.029 5203-5231/com.antonioleiva.weatherapp D/OpenGLRenderer: Swap behavior 1
11-19 16:57:51.030 5203-5231/com.antonioleiva.weatherapp W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-19 16:57:51.030 5203-5231/com.antonioleiva.weatherapp D/OpenGLRenderer: Swap behavior 0
11-19 16:57:51.032 5203-5231/com.antonioleiva.weatherapp D/EGL_emulation: eglCreateContext: 0xa73850c0: maj 2 min 0 rcv 2
11-19 16:57:51.035 5203-5231/com.antonioleiva.weatherapp D/EGL_emulation: eglMakeCurrent: 0xa73850c0: ver 2 0 (tinfo 0xa73832a0)
                                                                          
                                                                          [ 11-19 16:57:51.038  1902: 1911 W/         ]
                                                                          Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
11-19 16:57:51.063 5203-5231/com.antonioleiva.weatherapp D/EGL_emulation: eglMakeCurrent: 0xa73850c0: ver 2 0 (tinfo 0xa73832a0)

**Comment by gonpuga** [comment]
The problem is the zipCode because 94043 does not match any OpenWeatherMap code. And not only that, the free plan is also failing since last year and searching by zipCode fails frequently. Instead, city name can be used, making some changes in code (changing type from Long to String for now).

**Comment by antoniolg** [comment]
Yeah, the API of OpenWeatherMap changed, now `q` is not accepting zip codes. It needs to be `zip`. I updated the the main branch (https://github.com/antoniolg/Kotlin-for-Android-Developers/commit/c290ebc8e6a2b82cacc00af18a9d460f46329404) as a patch until I release a new update of the book.

My plan was to wait until 1.2 is released, but I think I'll start right away to have this fixed ASAP.
