### ISSUE TITLE
ServerClasses, gson and null properties

### ISSUE THREAD

**Issue by mateuyabar** [antoniolg/Kotlin-for-Android-Developers#26]
I have a doubt about the data classes in ServerClasses.tk.
This classes are popullated using GSon. When Gson creates the classes it will use a kind of empty constructor and it will fill the properties, therefore, there might be values that are null (in case the api changes for example). Shouldn't we put default values ensure no null properties?

**Comment by antoniolg** [comment]
I don't think so 🤔 . If it can be null, the property needs to be a nullable value. I can't say it 100% sure, but if that type is one of the value types in Java (int, long, etc), it'll probably use the default value for those types. For the rest, as in Java, it'll use `null`.
