### ISSUE TITLE
Change http links to https-- Android error

### ISSUE THREAD

**Issue by RyanDurk** [antoniolg/Kotlin-for-Android-Developers#30]
In MainActivity.kt, starting with Chapter 8, the http link gives me this error in MainActivity->onCreate:

> weatherapp W/System.err: java.io.IOException: Cleartext HTTP traffic to api.openweathermap.org not permitted

I propose changing the http://api.openweather... URL to https://api.openweather...

**Comment by SVNicolaeDaniel** [comment]
if not, please update manifest.

<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>

**Comment by cking24343** [comment]
According to Network security configuration: "Starting with Android 9.0 (API level 28), cleartext support is disabled by default." 

@SVNicolaeDaniel suggestion works. Can also look at the following for more options: [https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted](url)

**Comment by Mostafayehya** [comment]
> 
> 
> In MainActivity.kt, starting with Chapter 8, the http link gives me this error in MainActivity->onCreate:
> 
> > weatherapp W/System.err: java.io.IOException: Cleartext HTTP traffic to api.openweathermap.org not permitted
> 
> I propose changing the http://api.openweather... URL to https://api.openweather...

this solved the problem
